name: Checkov Terraform Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkov-scan:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Checkout repository
      uses: actions/checkout@v3

    - name: 2. Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: 3. Install Checkov
      run: |
        python -m pip install --upgrade pip
        pip install checkov

    - name: 4. Run Checkov on Terraform code
      run: |
        checkov -d .

    - name: 5. Generate JSON report
      run: |
        checkov -d . -o json > checkov_report.json

    - name: 6. Upload Checkov report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: checkov-report
        path: checkov_report.json
