name: Checkov Terraform Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkov-scan:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Checkout repository
      uses: actions/checkout@v3

    - name: 2. Checkov GitHub Action
      uses: bridgecrewio/checkov-action@v12
      with:
        # This will add both a CLI output to the console and create a results.sarif file
        output_format: cli,sarif
        output_file_path: console,results.sarif
      
    - name: 3. Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      
      # Results are generated only on a success or failure
      # this is required since GitHub by default won't run the next step
      # when the previous one has failed. Security checks that do not pass will 'fail'.
      # An alternative is to add `continue-on-error: true` to the previous step
      # Or 'soft_fail: true' to checkov.
      if: success() || failure()
      with:
        sarif_file: results.sarif
        
    # - name: 2. Set up Python
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.x'

    # - name: 3. Install Checkov
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install checkov

    # - name: 4. Run Checkov on Terraform code
    #   run: |
    #     checkov -d .

    # - name: 5. Generate JSON report
    #   if: always()
    #   run: |
    #     checkov -d . -o json > checkov_report.json

    # - name: 6. Upload Checkov report
    #   if: always()
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: checkov-report
    #     path: checkov_report.json
